# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
      path: modules/hal/cmsis
    - name: hal_ti
      revision: 277d70a65ab14d46bf1ec0935cf9bb28bbaa8ab9
      path: modules/hal/ti
    - name: mcuboot
      revision: c71d2186077f9fd5f6d1aa53ee3f09dc41ce78f6
      path: bootloader/mcuboot
    - name: mcumgr
      revision: 697e145d5ee5e4b400e9d7bceaec79f6ac29df7c
      path: modules/lib/mcumgr
    - name: net-tools
      revision: 41132e9220f8bc1223084975350c5e5f3b492afe
      path: tools/net-tools

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
